version: '3.8'

services:
  # 1. Message Broker (Redis)
  redis-broker:
    image: redis:7-alpine
    container_name: mermaid_redis
    ports:
      - "6379:6379"
    networks:
      - mermaid_network

  # 2. API Gateway (FastAPI)
  api-gateway:
    build: ./api
    container_name: mermaid_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis-broker:6379/0
    depends_on:
      - redis-broker
    networks:
      - mermaid_network
    volumes:
      - ./api:/app  # Hot-reload code khi dev

  # 3. AI Worker (Celery + Qwen3)
  ai-worker:
    build: ./model
    container_name: mermaid_worker
    environment:
      - REDIS_URL=redis://redis-broker:6379/0
      - MODEL_TYPE=qwen
      - HF_TOKEN=
      - HF_HOME=/data/huggingface # Cache model để không phải tải lại mỗi lần restart container
    depends_on:
      - redis-broker
    networks:
      - mermaid_network
    volumes:
      - ~/hf_cache:/data/huggingface # Volume để lưu model vĩnh viễn
    command: celery -A tasks worker --loglevel=info --pool=solo
    # --- Cấu hình GPU (Bỏ comment nếu dùng NVIDIA GPU) ---
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]

networks:
  mermaid_network:
